"""empty message

Revision ID: 5689b8f8ef90
Revises: 
Create Date: 2022-01-04 23:23:47.805648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5689b8f8ef90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_cash_movement_id', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_cash_movement_id')
    )
    op.create_index(op.f('ix_example_id'), 'example', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_id'), table_name='example')
    op.drop_table('example')
    # ### end Alembic commands ###
